#! /bin/sh
killall -9 sxhkd

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config top_padding          0
bspc config window_gap          12
bspc config focused_border_color "#b4f9f8"
bspc config presel_feedback_color "#7aa2f7"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


xsetroot -cursor_name left_ptr
nitrogen --restore

picom --experimental-backends &
setxkbmap -layout us &
~/.config/polybar/launch.sh &
