#! /bin/sh
killall "sxhkd"
killall "picom"
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	1
bspc config top_padding          	20
bspc config window_gap          	12
bspc config single_monocle 				true
bspc config normal_border_color #4c566a
bspc config focused_border_color #4c566a

bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bpsc rule -a Firefox desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


xsetroot -cursor_name left_ptr
nitrogen --restore

picom --experimental-backends &
setxkbmap -layout us &
~/.config/polybar/launch.sh &
